---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-service-account
spec:
  params:
    - name: sa
      type: string
      description: The name of the Service Account to create
    - name: namespace
      type: string
      description: Namespace that owns the service account being created
  steps:
    - name: apply-kubernetes-manifest
      image: quay.io/openshift/origin-cli:4.16
      script: |
        oc apply -f - <<EOF 
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: $(params.sa)
          namespace: $(params.namespace)
        EOF
